### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by Cantfirmed** [htl-perg-2019-20-5ahif/highscore-exercise-xxANONYMxx#1]
Dear Mr Stropek,

here is our solution with a SQL database.

Greetings
Samuel Lange, Stefan Wansch and Patrick Wegerer

**Comment by rstropek** [comment]
Hi @Cantfirmed!

Thank you for the solution, well done. You will get 2 points for POSE and 1 point for NVS MC.

I had to fix a CORS issue before I could execute the application successfully.

Greetings,
Rainer Stropek.
